### ISSUE TITLE
Extend deviceinfo to include hostname

### ISSUE THREAD

**Issue by eLtMosen** [AsteroidOS/qml-asteroid#22]
Following discussion on matrix, to enable watch model/codename identification within watchfaces.

**Comment by MagneFire** [comment]
I have this work in progress now over here: https://github.com/MagneFire/qml-asteroid/commits/feature/hostname

**Comment by FlorentRevest** [comment]
I think it's fair to have a function to get the device hostname (would it only be for system settings' about page) but I think it's a bad idea to use it to enable special hacks in watchfaces. The better fix for this would be to have specific booleans for each of these similarly to HAS_ROUND_SCREEN. For example, HAS_PHYSICAL_HOUR_DIAL could be used to determine whether the current device has indications for each individual watchface could just rely on this instead of having to maintain their own custom list of watches...

I could be somewhat tolerant towards using hostname in unofficial watchfaces along with a big warning comment that says it's a bad idea but if we ever want stock watchfaces to adapt their look based no watch features they should use specific qml-asteroid machine booleans rather than lists of watch codenames.
